image: jdrouet/docker-with-buildx:stable
services:
  - docker:dind
stages:
  - build

build:
  stage: build

  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker buildx create --use
    - docker buildx build --push --platform linux/arm64/v8 -t "$CI_REGISTRY_IMAGE" .
  only:
    - master
